CREATE CACHED TABLE USER (
    USER_ID INT AUTO_INCREMENT,
    USER_NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
	EMAIL_ID VARCHAR(50) NOT NULL,
	HOMETOWN VARCHAR(50) NOT NULL,
	MOBILE_NO VARCHAR(20) NOT NULL,
	SEX VARCHAR(10) NOT NULL,
	BIRTHDAY VARCHAR(20) NOT NULL
);
CREATE TABLE USER_IMAGE (
    USER_ID INT,
    IMAGE_PATH VARCHAR(500) NOT NULL, 
    FOREIGN KEY (USER_ID) 
    REFERENCES public.USER(USER_ID)
);
INSERT INTO USER(USER_NAME, PASSWORD, EMAIL_ID, HOMETOWN, MOBILE_NO, SEX, BIRTHDAY) VALUES
('admin', 'autodoc','yogesh.gunge@gmail.com','Pune','0123456789','Male','');
